describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative()
    await device.launchApp({ permissions: { notifications: 'YES' } })
  })
  it('should show hello screen after tap', async () => {
    await waitFor(element(by.type('RCTScrollView'))).toBeVisible()
    await element(by.type('RCTScrollView')).scrollTo('right')
    await waitFor(element(by.id('enterApp'))).toBeVisible()
    await element(by.id('enterApp')).tap()
    await element(by.text('我的')).tap()
    await element(by.text('立即登入')).tap()
    await element(by.text('你的手机号码')).typeText('13800000000')
    await element(by.text('接收到的验证码')).typeText('0000')
    await element(by.text('手机登入')).tap()
    await element(by.text('登入')).tap()
    await element(by.id('userCenter')).tap()
    await waitFor(element(by.text('+8613800000000'))).toBeVisible()
    await element(by.text('退出登入')).tap()
    await element(by.id('cancelLogin')).tap()

    await waitFor(element(by.type('RCTScrollView'))).toBeVisible()
    await element(by.type('RCTScrollView')).scrollTo('right')
    await waitFor(element(by.id('enterApp'))).toBeVisible()
    await element(by.id('enterApp')).tap()
    await element(by.text('我的')).tap()
    await element(by.text('立即登入')).tap()
    await element(by.text('你的手机号码')).typeText('13800000000')
    await element(by.text('接收到的验证码')).typeText('1234')
    await element(by.text('手机登入')).tap()
    await element(by.text('登入')).tap()
    await waitFor(element(by.text('+验证码不正确'))).toBeVisible()
    await element(by.text('关闭')).tap()
    await element(by.id('cancelLogin')).tap()
    await element(by.text('首页')).tap()
  })
})
